name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-16.04

    container:
      # https://hub.docker.com/_/microsoft-dotnet-core-sdk/
      image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: test
        shell: sh
        run: ./cake.sh -target=pack
